export const users = [
  {
    id: 1,
    lastName: 'Doe',
    firstName: 'John',
    middleName: '',
    gender: 'Male',
    birthday: new Date().toLocaleDateString('en-US'),
    maritalStatus: 'Single',
    contactNumber: '09123456789',
    citizenship: 'Filipino',
    email: 'john@gmail.com',
    address: '157 aguardiente',
    country: 'PH',
    fatherName: 'Papa',
    motherName: 'Mama',
    companyName: 'Sprout PH',
    position: 'Manager',
    companyAddress: 'Company Street',
    companyContactNumber: '417-999-222',
    tin: '111',
    sss: '222',
    pagibig: '333',
    status: 'Pending',
  },
  {
    id: 2,
    lastName: 'Evans',
    firstName: 'Chris',
    middleName: '',
    gender: 'Male',
    birthday: new Date(),
    maritalStatus: 'Single',
    contactNumber: '09123456789',
    citizenship: 'American',
    email: 'chris@gmail.com',
    address: 'New York Street',
    country: 'US',
    fatherName: '',
    motherName: '',
    companyName: 'Marvel',
    position: 'Actor',
    companyAddress: '',
    companyContactNumber: '',
    tin: '',
    sss: '',
    pagibig: '',
    status: 'Pending',
  },
  {
    id: 3,
    lastName: 'Smith',
    firstName: 'Jane',
    middleName: '',
    gender: 'Female',
    birthday: new Date(),
    maritalStatus: 'Single',
    contactNumber: '09123456789',
    citizenship: 'Filipino',
    email: 'jane@gmail.com',
    address: '157 aguardiente',
    country: 'PH',
    fatherName: '',
    motherName: '',
    companyName: 'Google',
    position: 'Product Manager',
    companyAddress: '',
    companyContactNumber: '09123456789',
    tin: '111',
    sss: '',
    pagibig: '',
    status: 'Pending',
  },
];
